server {
    listen 80;

    location /api/ {
        proxy_pass http://markitdown:8001/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_connect_timeout 420s;
        proxy_send_timeout 420s;
        proxy_read_timeout 420s;
        send_timeout 420s;
        client_max_body_size 100m;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri /index.html;
    }
}
